-- Local Runtime Agent baseline schema for MariaDB 11.8.
-- This is a manual deployment script. It intentionally does not drop tables.
-- Review existing tables before applying it to a non-empty database.

CREATE TABLE IF NOT EXISTS TB_M26_AGENT (
    AGENT_ID VARCHAR(64) PRIMARY KEY,
    HOSTNAME VARCHAR(256),
    OS_TYPE VARCHAR(32),
    IP_ADDRESS VARCHAR(45),
    SPRING_BOOT_VERSION VARCHAR(32),
    INSTALLED_AT TIMESTAMP NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TB_M26_MODEL_PROCESS (
    PROCESS_ID VARCHAR(64) PRIMARY KEY,
    AGENT_ID VARCHAR(64) NOT NULL,
    MODEL_NAME VARCHAR(256),
    MODEL_TYPE VARCHAR(64),
    EXECUTABLE_PATH VARCHAR(512),
    WORKING_DIRECTORY VARCHAR(512),
    COMMAND_ARGS LONGTEXT,
    ENV_VARS LONGTEXT,
    AUTO_RESTART BOOLEAN DEFAULT TRUE,
    MAX_RESTART_ATTEMPTS INT DEFAULT 3,
    RESTART_DELAY_SEC INT DEFAULT 10,
    TIMEOUT_SEC INT DEFAULT 3600,
    MEMORY_LIMIT_MB INT,
    CPU_LIMIT_PERCENT INT,
    HEALTH_CHECK_ENABLED BOOLEAN DEFAULT TRUE,
    HEALTH_CHECK_INTERVAL_SEC INT DEFAULT 30,
    HEALTH_CHECK_ENDPOINT VARCHAR(512),
    PROCESS_STATE VARCHAR(32),
    PROCESS_PID INT,
    CPU_PERCENT DECIMAL(5,2),
    MEMORY_MB INT,
    LAST_HEALTH_CHECK TIMESTAMP NULL,
    LAST_HEARTBEAT TIMESTAMP NULL,
    HEALTH_STATUS VARCHAR(32),
    UPTIME_SEC BIGINT,
    CRASH_COUNT INT DEFAULT 0,
    LAST_CRASH_TIME TIMESTAMP NULL,
    ERROR_MESSAGE LONGTEXT,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX IDX_M26_MODEL_PROCESS_AGENT
    ON TB_M26_MODEL_PROCESS (AGENT_ID, PROCESS_ID);

CREATE TABLE IF NOT EXISTS TB_M26_COMMAND (
    COMMAND_ID VARCHAR(64) PRIMARY KEY,
    AGENT_ID VARCHAR(64) NOT NULL,
    PROCESS_ID VARCHAR(64),
    COMMAND_TYPE VARCHAR(32),
    COMMAND_STATUS VARCHAR(32),
    COMMAND_PARAMETERS LONGTEXT,
    PROCESSED_AT TIMESTAMP NULL,
    FAILED_REASON LONGTEXT,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE INDEX IDX_M26_COMMAND_PENDING
    ON TB_M26_COMMAND (AGENT_ID, COMMAND_STATUS);

CREATE TABLE IF NOT EXISTS TB_M26_MODEL_PARAMETER (
    PARAMETER_ID VARCHAR(64) PRIMARY KEY,
    PROCESS_ID VARCHAR(64) NOT NULL,
    PARAM_KEY VARCHAR(256),
    PARAM_VALUE LONGTEXT,
    PARAM_TYPE VARCHAR(32),
    PARAM_VERSION INT DEFAULT 1,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TB_M26_EXECUTION_LOG (
    LOG_ID VARCHAR(64) PRIMARY KEY,
    AGENT_ID VARCHAR(64),
    PROCESS_ID VARCHAR(64),
    COMMAND_TYPE VARCHAR(32),
    EXECUTION_STATUS VARCHAR(32),
    EXIT_CODE INT,
    STDOUT_PREVIEW TEXT,
    STDERR_PREVIEW TEXT,
    DURATION_SEC INT,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IDX_M26_EXECUTION_LOG_PROCESS_TIME
    ON TB_M26_EXECUTION_LOG (PROCESS_ID, CREATED_TIMESTAMP);
