-- Replace the values below with the actual machine and process values.
-- The agent resolves its identity from TB_M26_AGENT.IP_ADDRESS.

SET @agent_id = 'agent-local-01';
SET @agent_ip = '192.168.0.7';
SET @hostname = 'LOCAL-PC';
SET @process_id = 'model-local-01';
SET @executable_path = 'C:/models/example/start.py';
SET @working_directory = 'C:/models/example';

INSERT INTO TB_M26_AGENT (
    AGENT_ID, HOSTNAME, OS_TYPE, IP_ADDRESS, INSTALLED_AT
) VALUES (
    @agent_id, @hostname, 'WINDOWS', @agent_ip, CURRENT_TIMESTAMP()
)
ON DUPLICATE KEY UPDATE
    HOSTNAME = VALUES(HOSTNAME),
    IP_ADDRESS = VALUES(IP_ADDRESS),
    LAST_UPDATED_TIMESTAMP = CURRENT_TIMESTAMP();

INSERT INTO TB_M26_MODEL_PROCESS (
    PROCESS_ID,
    AGENT_ID,
    MODEL_NAME,
    MODEL_TYPE,
    EXECUTABLE_PATH,
    WORKING_DIRECTORY,
    COMMAND_ARGS,
    ENV_VARS,
    AUTO_RESTART,
    MAX_RESTART_ATTEMPTS,
    RESTART_DELAY_SEC,
    TIMEOUT_SEC,
    HEALTH_CHECK_ENABLED,
    HEALTH_CHECK_INTERVAL_SEC,
    PROCESS_STATE,
    CRASH_COUNT
) VALUES (
    @process_id,
    @agent_id,
    'Example Model',
    'RUNTIME',
    @executable_path,
    @working_directory,
    JSON_ARRAY(),
    JSON_OBJECT(),
    1,
    3,
    10,
    3600,
    1,
    30,
    'STOPPED',
    0
)
ON DUPLICATE KEY UPDATE
    AGENT_ID = VALUES(AGENT_ID),
    EXECUTABLE_PATH = VALUES(EXECUTABLE_PATH),
    WORKING_DIRECTORY = VALUES(WORKING_DIRECTORY),
    COMMAND_ARGS = VALUES(COMMAND_ARGS),
    ENV_VARS = VALUES(ENV_VARS),
    AUTO_RESTART = VALUES(AUTO_RESTART),
    MAX_RESTART_ATTEMPTS = VALUES(MAX_RESTART_ATTEMPTS),
    RESTART_DELAY_SEC = VALUES(RESTART_DELAY_SEC),
    TIMEOUT_SEC = VALUES(TIMEOUT_SEC),
    HEALTH_CHECK_ENABLED = VALUES(HEALTH_CHECK_ENABLED),
    HEALTH_CHECK_INTERVAL_SEC = VALUES(HEALTH_CHECK_INTERVAL_SEC);

SELECT AGENT_ID, HOSTNAME, IP_ADDRESS
FROM TB_M26_AGENT
WHERE AGENT_ID = @agent_id;

SELECT PROCESS_ID, AGENT_ID, EXECUTABLE_PATH, PROCESS_STATE, AUTO_RESTART
FROM TB_M26_MODEL_PROCESS
WHERE AGENT_ID = @agent_id;
