-- Run after starting the Agent. Replace the IP with the machine being tested.
SET @local_ip = '192.168.0.7';

SELECT AGENT_ID,
       HOSTNAME,
       IP_ADDRESS,
       INSTALLED_AT,
       CASE WHEN IP_ADDRESS = @local_ip THEN 'OK' ELSE 'CHECK_IP' END AS IP_CHECK
FROM TB_M26_AGENT
WHERE IP_ADDRESS = @local_ip;

SELECT p.PROCESS_ID,
       p.AGENT_ID,
       p.MODEL_NAME,
       p.EXECUTABLE_PATH,
       p.PROCESS_STATE,
       p.PROCESS_PID,
       p.HEALTH_STATUS,
       p.LAST_HEARTBEAT
FROM TB_M26_MODEL_PROCESS p
JOIN TB_M26_AGENT a ON a.AGENT_ID = p.AGENT_ID
WHERE a.IP_ADDRESS = @local_ip
ORDER BY p.PROCESS_ID;

SELECT a.AGENT_ID,
       COUNT(p.PROCESS_ID) AS PROCESS_COUNT,
       SUM(CASE WHEN p.PROCESS_STATE = 'RUNNING' THEN 1 ELSE 0 END) AS RUNNING_COUNT,
       MAX(p.LAST_HEARTBEAT) AS LAST_HEARTBEAT
FROM TB_M26_AGENT a
LEFT JOIN TB_M26_MODEL_PROCESS p ON p.AGENT_ID = a.AGENT_ID
WHERE a.IP_ADDRESS = @local_ip
GROUP BY a.AGENT_ID;
