-- Run this script against the target MariaDB schema before starting the agent.
-- It reports missing tables/columns and must not change application data.

SELECT TABLE_NAME,
       CASE WHEN TABLE_NAME IS NULL THEN 'MISSING' ELSE 'OK' END AS TABLE_STATUS
FROM (
    SELECT 'TB_M26_AGENT' AS TABLE_NAME
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS'
    UNION ALL SELECT 'TB_M26_COMMAND'
    UNION ALL SELECT 'TB_M26_EXECUTION_LOG'
    UNION ALL SELECT 'TB_M26_MODEL_PARAMETER'
) required_tables
LEFT JOIN information_schema.TABLES actual
    ON actual.TABLE_SCHEMA = DATABASE()
   AND actual.TABLE_NAME = required_tables.TABLE_NAME;

SELECT required_columns.TABLE_NAME,
       required_columns.COLUMN_NAME,
       CASE WHEN actual.COLUMN_NAME IS NULL THEN 'MISSING' ELSE 'OK' END AS COLUMN_STATUS
FROM (
    SELECT 'TB_M26_AGENT' AS TABLE_NAME, 'AGENT_ID' AS COLUMN_NAME
    UNION ALL SELECT 'TB_M26_AGENT', 'IP_ADDRESS'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'PROCESS_ID'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'AGENT_ID'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'EXECUTABLE_PATH'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'WORKING_DIRECTORY'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'COMMAND_ARGS'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'ENV_VARS'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'AUTO_RESTART'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'MAX_RESTART_ATTEMPTS'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'RESTART_DELAY_SEC'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'TIMEOUT_SEC'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'MEMORY_LIMIT_MB'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'CPU_LIMIT_PERCENT'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'HEALTH_CHECK_ENABLED'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'HEALTH_CHECK_INTERVAL_SEC'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'HEALTH_CHECK_ENDPOINT'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'PROCESS_STATE'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'PROCESS_PID'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'CPU_PERCENT'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'MEMORY_MB'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'LAST_HEALTH_CHECK'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'LAST_HEARTBEAT'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'HEALTH_STATUS'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'UPTIME_SEC'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'CRASH_COUNT'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'LAST_CRASH_TIME'
    UNION ALL SELECT 'TB_M26_MODEL_PROCESS', 'ERROR_MESSAGE'
    UNION ALL SELECT 'TB_M26_COMMAND', 'COMMAND_ID'
    UNION ALL SELECT 'TB_M26_COMMAND', 'AGENT_ID'
    UNION ALL SELECT 'TB_M26_COMMAND', 'PROCESS_ID'
    UNION ALL SELECT 'TB_M26_COMMAND', 'COMMAND_TYPE'
    UNION ALL SELECT 'TB_M26_COMMAND', 'COMMAND_STATUS'
    UNION ALL SELECT 'TB_M26_COMMAND', 'COMMAND_PARAMETERS'
    UNION ALL SELECT 'TB_M26_COMMAND', 'PROCESSED_AT'
    UNION ALL SELECT 'TB_M26_COMMAND', 'FAILED_REASON'
    UNION ALL SELECT 'TB_M26_EXECUTION_LOG', 'LOG_ID'
    UNION ALL SELECT 'TB_M26_EXECUTION_LOG', 'AGENT_ID'
    UNION ALL SELECT 'TB_M26_EXECUTION_LOG', 'PROCESS_ID'
    UNION ALL SELECT 'TB_M26_EXECUTION_LOG', 'COMMAND_TYPE'
    UNION ALL SELECT 'TB_M26_EXECUTION_LOG', 'EXECUTION_STATUS'
    UNION ALL SELECT 'TB_M26_EXECUTION_LOG', 'EXIT_CODE'
    UNION ALL SELECT 'TB_M26_EXECUTION_LOG', 'STDOUT_PREVIEW'
    UNION ALL SELECT 'TB_M26_EXECUTION_LOG', 'STDERR_PREVIEW'
    UNION ALL SELECT 'TB_M26_EXECUTION_LOG', 'DURATION_SEC'
) required_columns
LEFT JOIN information_schema.COLUMNS actual
    ON actual.TABLE_SCHEMA = DATABASE()
   AND actual.TABLE_NAME = required_columns.TABLE_NAME
   AND actual.COLUMN_NAME = required_columns.COLUMN_NAME
ORDER BY required_columns.TABLE_NAME, required_columns.COLUMN_NAME;

SELECT TABLE_NAME AS LEGACY_TABLE,
       'REMOVE_OR_ARCHIVE_BEFORE_START' AS ACTION_REQUIRED
FROM information_schema.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'TB_M26_PROCESS_CONFIG';
