-- Local Runtime Agent - Enterprise Standard Schema (ARCHITECTURE.md §5)
-- Dialect: MariaDB 11.8
-- Clean slate: Drop old tables, create TB_M26_* only

-- Drop existing tables if they exist (legacy cleanup)
DROP TABLE IF EXISTS execution_log;
DROP TABLE IF EXISTS heartbeat_log;
DROP TABLE IF EXISTS model_parameters;
DROP TABLE IF EXISTS commands;
DROP TABLE IF EXISTS agent_status;
DROP TABLE IF EXISTS process_config;
DROP TABLE IF EXISTS agent_info;
DROP TABLE IF EXISTS TB_M26_EXECUTION_LOG;
DROP TABLE IF EXISTS TB_M26_MODEL_PARAMETER;
DROP TABLE IF EXISTS TB_M26_COMMAND;
DROP TABLE IF EXISTS TB_M26_MODEL_PROCESS;
DROP TABLE IF EXISTS TB_M26_PROCESS_CONFIG;
DROP TABLE IF EXISTS TB_M26_AGENT;
DROP VIEW IF EXISTS V_M26_MODEL_STATUS;

-- TB_M26_AGENT: Local Runtime Agent 정보
CREATE TABLE TB_M26_AGENT (
    CREATED_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    CREATED_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    CREATED_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    LAST_UPDATED_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    LAST_UPDATED_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    LAST_UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_END_STATUS VARCHAR(1) DEFAULT 'N',
    DATA_END_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    DATA_END_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    DATA_END_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    DATA_END_TIMESTAMP TIMESTAMP DEFAULT NULL,

    AGENT_ID VARCHAR(22) PRIMARY KEY,
    HOSTNAME VARCHAR(256),
    OS_TYPE VARCHAR(32),
    IP_ADDRESS VARCHAR(45),
    SPRING_BOOT_VERSION VARCHAR(32),
    INSTALLED_AT TIMESTAMP
);

-- TB_M26_PROCESS_CONFIG: 프로세스 설정
CREATE TABLE TB_M26_PROCESS_CONFIG (
    CREATED_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    CREATED_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    CREATED_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    LAST_UPDATED_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    LAST_UPDATED_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    LAST_UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_END_STATUS VARCHAR(1) DEFAULT 'N',
    DATA_END_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    DATA_END_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    DATA_END_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    DATA_END_TIMESTAMP TIMESTAMP DEFAULT NULL,

    PROCESS_ID VARCHAR(22) PRIMARY KEY,
    AGENT_ID VARCHAR(22) NOT NULL,
    MODEL_NAME VARCHAR(256),
    MODEL_TYPE VARCHAR(64),
    EXECUTABLE_PATH VARCHAR(512),
    WORKING_DIRECTORY VARCHAR(512),
    COMMAND_ARGS TEXT,
    ENV_VARS TEXT,
    AUTO_RESTART VARCHAR(1) DEFAULT 'Y',
    MAX_RESTART_ATTEMPTS INT DEFAULT 3,
    RESTART_DELAY_SEC INT DEFAULT 10,
    TIMEOUT_SEC INT DEFAULT 3600,
    MEMORY_LIMIT_MB INT,
    CPU_LIMIT_PERCENT INT,
    HEALTH_CHECK_ENABLED VARCHAR(1) DEFAULT 'Y',
    HEALTH_CHECK_INTERVAL_SEC INT DEFAULT 30,
    HEALTH_CHECK_ENDPOINT VARCHAR(512),
    METADATA TEXT
);

-- TB_M26_MODEL_PROCESS: 모델 프로세스 상태 (PROCESS_ID를 PK로 사용)
CREATE TABLE TB_M26_MODEL_PROCESS (
    CREATED_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    CREATED_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    CREATED_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    LAST_UPDATED_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    LAST_UPDATED_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    LAST_UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_END_STATUS VARCHAR(1) DEFAULT 'N',
    DATA_END_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    DATA_END_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    DATA_END_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    DATA_END_TIMESTAMP TIMESTAMP DEFAULT NULL,

    PROCESS_ID VARCHAR(22) PRIMARY KEY,
    AGENT_ID VARCHAR(22) NOT NULL,
    PROCESS_STATE VARCHAR(32),
    PROCESS_PID INT,
    CPU_PERCENT DECIMAL(5,2),
    MEMORY_MB INT,
    HEALTH_STATUS VARCHAR(32),
    UPTIME_SEC BIGINT,
    CRASH_COUNT INT DEFAULT 0,
    LAST_HEALTH_CHECK TIMESTAMP,
    LAST_CRASH_TIME TIMESTAMP,
    LAST_HEARTBEAT TIMESTAMP,
    ERROR_MESSAGE TEXT
);

CREATE INDEX IDX_AGENT_PROCESS ON TB_M26_MODEL_PROCESS (AGENT_ID, PROCESS_ID);

-- TB_M26_COMMAND: 명령 큐
CREATE TABLE TB_M26_COMMAND (
    CREATED_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    CREATED_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    CREATED_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    LAST_UPDATED_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    LAST_UPDATED_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    LAST_UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_END_STATUS VARCHAR(1) DEFAULT 'N',
    DATA_END_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    DATA_END_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    DATA_END_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    DATA_END_TIMESTAMP TIMESTAMP DEFAULT NULL,

    COMMAND_ID VARCHAR(22) PRIMARY KEY,
    AGENT_ID VARCHAR(22) NOT NULL,
    PROCESS_ID VARCHAR(22),
    COMMAND_TYPE VARCHAR(32),
    COMMAND_STATUS VARCHAR(32),
    COMMAND_PARAMETERS TEXT,
    PROCESSED_AT TIMESTAMP,
    FAILED_REASON TEXT
);

CREATE INDEX IDX_PENDING ON TB_M26_COMMAND (COMMAND_STATUS, AGENT_ID);

-- TB_M26_MODEL_PARAMETER: 모델 파라미터
CREATE TABLE TB_M26_MODEL_PARAMETER (
    CREATED_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    CREATED_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    CREATED_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    LAST_UPDATED_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    LAST_UPDATED_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    LAST_UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_END_STATUS VARCHAR(1) DEFAULT 'N',
    DATA_END_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    DATA_END_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    DATA_END_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    DATA_END_TIMESTAMP TIMESTAMP DEFAULT NULL,

    PARAMETER_ID VARCHAR(22) PRIMARY KEY,
    PROCESS_ID VARCHAR(22) NOT NULL,
    PARAM_KEY VARCHAR(256),
    PARAM_VALUE TEXT,
    PARAM_TYPE VARCHAR(32),
    PARAM_VERSION INT DEFAULT 1,
    IS_ACTIVE VARCHAR(1) DEFAULT 'Y'
);

-- TB_M26_EXECUTION_LOG: 실행 로그
CREATE TABLE TB_M26_EXECUTION_LOG (
    CREATED_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    CREATED_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    CREATED_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    LAST_UPDATED_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    LAST_UPDATED_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    LAST_UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_END_STATUS VARCHAR(1) DEFAULT 'N',
    DATA_END_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    DATA_END_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    DATA_END_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    DATA_END_TIMESTAMP TIMESTAMP DEFAULT NULL,

    LOG_ID VARCHAR(22) PRIMARY KEY,
    AGENT_ID VARCHAR(22),
    PROCESS_ID VARCHAR(22),
    COMMAND_TYPE VARCHAR(32),
    EXECUTION_STATUS VARCHAR(32),
    EXIT_CODE INT,
    STDOUT_PREVIEW TEXT,
    STDERR_PREVIEW TEXT,
    DURATION_SEC INT
);

CREATE INDEX IDX_PROCESS_TIME ON TB_M26_EXECUTION_LOG (PROCESS_ID, CREATED_TIMESTAMP);

-- V_M26_MODEL_STATUS: 통합 상태 뷰 (중앙 서버 대시보드용)
CREATE VIEW V_M26_MODEL_STATUS AS
SELECT
    ai.AGENT_ID,
    ai.HOSTNAME,
    pc.PROCESS_ID,
    pc.MODEL_NAME,
    mp.PROCESS_STATE,
    mp.PROCESS_PID,
    mp.CPU_PERCENT,
    mp.MEMORY_MB,
    mp.HEALTH_STATUS,
    mp.UPTIME_SEC,
    mp.CRASH_COUNT,
    mp.LAST_HEALTH_CHECK,
    COUNT(CASE WHEN c.COMMAND_STATUS = 'PENDING' THEN 1 END) as PENDING_COMMANDS
FROM TB_M26_AGENT ai
JOIN TB_M26_PROCESS_CONFIG pc ON ai.AGENT_ID = pc.AGENT_ID AND ai.DATA_END_STATUS = 'N' AND pc.DATA_END_STATUS = 'N'
LEFT JOIN TB_M26_MODEL_PROCESS mp ON pc.PROCESS_ID = mp.PROCESS_ID AND mp.DATA_END_STATUS = 'N'
LEFT JOIN TB_M26_COMMAND c ON ai.AGENT_ID = c.AGENT_ID AND c.COMMAND_STATUS = 'PENDING' AND c.DATA_END_STATUS = 'N'
GROUP BY ai.AGENT_ID, pc.PROCESS_ID;
